// VirtualBoy servo board emulator, VirtualTap-synchronised variant of servo_emu.c
// For ATTiny25, internal RC osc, CKDIV8 off
// Fuses Ex:0xFF High:0xDF Low:0xE2 (same as servo_emu.c)
// Part of the VirtualTap project
// 2018 Furrtek, sync input 2026
//
// Difference from servo_emu.c: PB2 is an input instead of the main sync output. VirtualTap's
// SERVO_SYNC (J1 "V_HS" pad, PAL "servo master" bitstream) is wired to the VB pin 6 net, so it
// drives the VB's main sync directly and this chip listens to it with INT0. Every rising edge
// restarts the 20 ms cycle, so eye A/B and the frame duration bytes follow VirtualTap's frame
// timing, and VirtualTap moves this edge by one line (64 us) per frame until the VB's transfer
// burst sits in its vertical blanking. Without VirtualTap connected (PB2 held high by its pull-up)
// the cycle free-runs at 24 ms (fallback at tick 480), so this is still a servo emulator, slow.
//
// Build: as servo_emu.c (tl866_programmer/Makefile with servo_emu.c replaced by this file).
// If the sync wire goes through an inverting buffer/transistor, define SYNC_INVERTED.
//
// MCU     VB
// PB3(2): Pin 4 (clk)
// PB4(3): Pin 5 (data)
// GND(4): Pin 1
// PB0(5): Pin 8 (eye A sync feedback)
// PB1(6): Pin 9 (eye B sync feedback)
// PB2(7): Pin 6 (main 50Hz sync) = INPUT, driven by VirtualTap SERVO_SYNC
// VCC(8): Pin 3

#include <inttypes.h>
#include <avr/io.h>
#include <avr/interrupt.h>

#define TIMING_DATA 0xA4	// Approx. value when oscillation is stable

// Tick numbers below count from the main sync rising edge (tick 180 of servo_emu.c's cycle).
// servo_emu.c: eye B high 200, data 210, eye A low 240, data 252, main low 380, eye A high 400,
// eye B low 40, main high 180.
#define T_EYEB_HIGH 20
#define T_DATA1 30
#define T_EYEA_LOW 60
#define T_DATA2 72
#define T_EYEA_HIGH 220
#define T_EYEB_LOW 260
#define T_FREERUN 480		// No edge came (VirtualTap absent): restart on our own, 24 ms. Must be later than
							// VirtualTap's longest cycle (8-line hold: 322 lines = 20.62 ms) even with the RC
							// 10 % fast (480 x 45.5 us = 21.8 ms), or the cycle restarts twice in one frame

uint8_t volatile data_step = 0xFF, data_sr;
uint16_t volatile tmr = 0;

// Main sync rising edge from VirtualTap: restart the cycle, re-phase the 50us tick
ISR(INT0_vect) {
	tmr = 0;
	TCNT0 = 0;
}

// Interrupt occurs every 50us
ISR(TIM0_COMPA_vect) {
	tmr++;

	// Generate sync signals with appropriate phases
	// Measured from real servo board
	// Eyes: 8ms low, 12ms high
	// Sync: 10ms low, 10ms high (generated by VirtualTap, edge received on PB2)
	if (tmr == T_EYEB_HIGH) {
		PORTB |= 2;		// Eye B feedback high
	} else if (tmr == T_DATA1) {
		data_step = 0;	// Start sending frame duration
		data_sr = TIMING_DATA;
	} else if (tmr == T_EYEA_LOW) {
		PORTB &= ~1;	// Eye A feedback low
	} else if (tmr == T_DATA2) {
		data_step = 0;	// Start sending frame duration
		data_sr = TIMING_DATA;
	} else if (tmr == T_EYEA_HIGH) {
		PORTB |= 1;		// Eye A feedback high
	} else if (tmr == T_EYEB_LOW) {
		PORTB &= ~2;	// Eye B feedback low
	} else if (tmr == T_FREERUN) {
		tmr = 0;		// Fallback, normally INT0 restarts the cycle first
	}

	if (data_step != 0xFF) {
		// Send 8-bit frame duration

		// Clock
		if (data_step & 1) {
			PORTB |= 8;
		} else {
			PORTB &= ~8;
			// Data
			if (data_sr & 0x80)
				PORTB |= 16;
			else
				PORTB &= ~16;
			data_sr <<= 1;
		}

		if (data_step == 16)
			data_step = 0xFF;	// Done
		else
			data_step++;
	}
}

int main(void) {
	MCUSR &= ~(1<<WDRF);	// Watchdog sleepies -_-
	WDTCR = (1<<WDCE) | (1<<WDE);
	WDTCR = 0x00;

	DDRB = 0b00011011;		// PB0, PB1, PB3, PB4 outputs, PB2 input
	PORTB = 0b00000100;		// Pull-up on PB2 so an open sync wire does not float into INT0

	OCR0A = 49;				// 8M/8/(49+1) = 20kHz (50us)
	TCCR0A = 0b00000010;	// CTC
	TCCR0B = 0b00000010;	// Prescaler = 8
	TIMSK = 0b00010000;		// Match A interrupt

#ifdef SYNC_INVERTED
	MCUCR = (1<<ISC01);					// INT0 on falling edge
#else
	MCUCR = (1<<ISC01) | (1<<ISC00);	// INT0 on rising edge
#endif
	GIMSK = (1<<INT0);

	sei();

	for (;;) { }

    return 0;
}
